export interface Destination {
  id: string;
  emoji: string;
  name: string;
  country: string;
  countryCode: string;
  tagline: string;
  description: string;
  days: number;
  budgetUSD: number;
  ratingAverage: number;
  cloneCount: number;
  tags: string[];
  personas: string[];
  bestSeason: string;
  coverGradient: string;
  highlights: string[];
  hiddenGem: string;
}

export const Destinations: Destination[] = [
  {
    id: 'paris',
    emoji: '🗼',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    tagline: 'The City of Light and Love',
    description: 'Walk along the Seine, explore world-class museums, and savor iconic French cuisine in the most romantic city on Earth.',
    days: 5,
    budgetUSD: 2000,
    ratingAverage: 4.9,
    cloneCount: 2341,
    tags: ['romantic', 'culture', 'food'],
    personas: ['couple', 'friends', 'solo'],
    bestSeason: 'April-May, September-October',
    coverGradient: 'linear-gradient(135deg, #FF5533, #F5A020)',
    highlights: [
      'Eiffel Tower at sunset',
      'Louvre Museum masterpieces',
      'Montmartre artistic streets',
    ],
    hiddenGem: 'Visit Sainte-Chapelle at dusk when the stained glass windows glow without crowds.',
  },
  {
    id: 'tokyo',
    emoji: '🌃',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    tagline: 'Ancient traditions meet cutting-edge modernity',
    description: 'Experience serene temples, vibrant street culture, world-class food, and cutting-edge technology in Japan\'s capital.',
    days: 6,
    budgetUSD: 2200,
    ratingAverage: 4.8,
    cloneCount: 1987,
    tags: ['culture', 'food', 'city'],
    personas: ['family', 'friends', 'solo'],
    bestSeason: 'March-May, September-November',
    coverGradient: 'linear-gradient(135deg, #7755F0, #0BAADF)',
    highlights: [
      'Senso-ji Temple and Nakamise',
      'Shibuya Crossing energy',
      'Tsukiji fish market cuisine',
    ],
    hiddenGem: 'Find tiny ramen shops in Shinjuku\'s Omoide Yokocho alley for authentic, under-the-radar dining.',
  },
  {
    id: 'bali',
    emoji: '🏝️',
    name: 'Bali',
    country: 'Indonesia',
    countryCode: 'ID',
    tagline: 'Spiritual temples and pristine beaches',
    description: 'Discover ancient Hindu temples, lush rice paddies, world-class beaches, and a thriving wellness culture.',
    days: 7,
    budgetUSD: 1200,
    ratingAverage: 4.7,
    cloneCount: 3421,
    tags: ['beach', 'wellness', 'budget'],
    personas: ['couple', 'friends', 'solo'],
    bestSeason: 'April-October',
    coverGradient: 'linear-gradient(135deg, #0BBFA0, #0BAADF)',
    highlights: [
      'Ubud rice terraces',
      'Tanah Lot temple',
      'Seminyak beach clubs',
    ],
    hiddenGem: 'Head to Amed for peaceful black sand beaches and world-class diving without the crowds.',
  },
  {
    id: 'patagonia',
    emoji: '🏔️',
    name: 'Patagonia',
    country: 'Chile & Argentina',
    countryCode: 'CL',
    tagline: 'Dramatic peaks, glaciers, and pristine wilderness',
    description: 'Trek amongst snow-capped mountains, witness colossal glaciers, and experience some of South America\'s most untamed beauty.',
    days: 10,
    budgetUSD: 3500,
    ratingAverage: 4.9,
    cloneCount: 892,
    tags: ['adventure', 'nature', 'mountains'],
    personas: ['friends', 'solo', 'adventure-seekers'],
    bestSeason: 'December-February',
    coverGradient: 'linear-gradient(135deg, #FF5533, #7755F0)',
    highlights: [
      'Torres del Paine trekking',
      'Perito Moreno Glacier',
      'Fitz Roy mountain views',
    ],
    hiddenGem: 'Camp at Laguna de los Tres in the early morning for sunrise reflection views that few tourists witness.',
  },
  {
    id: 'rome',
    emoji: '🏛️',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    tagline: 'The Eternal City of history and passion',
    description: 'Walk through millennia of history, marvel at Renaissance art, enjoy world-famous pasta, and soak in la dolce vita.',
    days: 4,
    budgetUSD: 1800,
    ratingAverage: 4.8,
    cloneCount: 2156,
    tags: ['history', 'culture', 'food'],
    personas: ['couple', 'family', 'solo'],
    bestSeason: 'April-May, September-October',
    coverGradient: 'linear-gradient(135deg, #EF3F6A, #FF5533)',
    highlights: [
      'Colosseum and Roman Forum',
      'Vatican Museums and Sistine Chapel',
      'Trevi Fountain at night',
    ],
    hiddenGem: 'Wake up early to visit the Pantheon before 9am when it\'s serene and light pours through the oculus.',
  },
  {
    id: 'maldives',
    emoji: '🌴',
    name: 'Maldives',
    country: 'Maldives',
    countryCode: 'MV',
    tagline: 'Overwater luxury and turquoise paradise',
    description: 'Stay in overwater bungalows, snorkel pristine coral reefs, and experience ultimate tropical indulgence.',
    days: 5,
    budgetUSD: 4500,
    ratingAverage: 4.9,
    cloneCount: 1234,
    tags: ['beach', 'luxury', 'snorkeling'],
    personas: ['couple', 'family'],
    bestSeason: 'November-April',
    coverGradient: 'linear-gradient(135deg, #0BAADF, #0BBFA0)',
    highlights: [
      'Overwater bungalows',
      'Coral reef snorkeling',
      'Sunset dolphin cruise',
    ],
    hiddenGem: 'Book an island-hopping local dhoni cruise to spot manta rays and experience authentic Maldivian culture.',
  },
  {
    id: 'newyork',
    emoji: '🎭',
    name: 'New York',
    country: 'USA',
    countryCode: 'US',
    tagline: 'The city that never sleeps',
    description: 'Experience iconic landmarks, world-class museums, diverse neighborhoods, and endless entertainment options.',
    days: 4,
    budgetUSD: 2500,
    ratingAverage: 4.7,
    cloneCount: 1876,
    tags: ['city', 'culture', 'nightlife'],
    personas: ['friends', 'couple', 'solo'],
    bestSeason: 'September-November, March-May',
    coverGradient: 'linear-gradient(135deg, #FF5533, #EF3F6A)',
    highlights: [
      'Times Square and Broadway',
      'Central Park picnics',
      'NYC museums and galleries',
    ],
    hiddenGem: 'Catch live jazz at Blue Note without a ticket by standing at the bar and buying drinks.',
  },
  {
    id: 'santorini',
    emoji: '🌅',
    name: 'Santorini',
    country: 'Greece',
    countryCode: 'GR',
    tagline: 'Whitewashed cliffs and Aegean sunsets',
    description: 'Marvel at spectacular caldera views, relax on unique volcanic beaches, and savor Mediterranean cuisine.',
    days: 3,
    budgetUSD: 1500,
    ratingAverage: 4.8,
    cloneCount: 2987,
    tags: ['beach', 'romantic', 'culture'],
    personas: ['couple', 'friends', 'family'],
    bestSeason: 'April-May, September-October',
    coverGradient: 'linear-gradient(135deg, #EF3F6A, #FF5533)',
    highlights: [
      'Oia sunset views',
      'Fira clifftop town',
      'Red beach swimming',
    ],
    hiddenGem: 'Hike the caldera trail from Fira to Oia at sunrise for empty pathways and magical golden light.',
  },
  {
    id: 'mexicocity',
    emoji: '🌮',
    name: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    tagline: 'Aztec heritage meets vibrant modernity',
    description: 'Explore world-class museums, ancient pyramids, street art, and some of the world\'s best tacos.',
    days: 4,
    budgetUSD: 1300,
    ratingAverage: 4.6,
    cloneCount: 1543,
    tags: ['city', 'food', 'culture'],
    personas: ['friends', 'solo', 'family'],
    bestSeason: 'November-April',
    coverGradient: 'linear-gradient(135deg, #FF5533, #F5A020)',
    highlights: [
      'Frida Kahlo\'s La Casa Azul',
      'Templo Mayor ruins',
      'Street food and markets',
    ],
    hiddenGem: 'Visit Anahuacalli Museum (Frida\'s secret pyramid museum) for intimate art without crowds.',
  },
  {
    id: 'lisbon',
    emoji: '🇵🇹',
    name: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    tagline: 'Colorful tiles and Atlantic charm',
    description: 'Discover pastel neighborhoods, tile art, stunning lookouts, and authentic Portuguese cuisine at bargain prices.',
    days: 4,
    budgetUSD: 1000,
    ratingAverage: 4.7,
    cloneCount: 1654,
    tags: ['budget', 'culture', 'city'],
    personas: ['solo', 'friends', 'family'],
    bestSeason: 'April-May, September-October',
    coverGradient: 'linear-gradient(135deg, #F5A020, #EF3F6A)',
    highlights: [
      'Alfama historic neighborhood',
      'São Jorge Castle views',
      'Pastel de Nata pastries',
    ],
    hiddenGem: 'Ride Tram 28 to Graça at dusk for sunset views over the city from a vintage yellow tram.',
  },
  {
    id: 'serengeti',
    emoji: '🦁',
    name: 'Serengeti',
    country: 'Tanzania',
    countryCode: 'TZ',
    tagline: 'The Great Migration and African wilderness',
    description: 'Witness the greatest wildlife spectacle on Earth with lion, zebra, and wildebeest migrations.',
    days: 5,
    budgetUSD: 4000,
    ratingAverage: 4.9,
    cloneCount: 654,
    tags: ['adventure', 'nature', 'wildlife'],
    personas: ['family', 'friends', 'adventure-seekers'],
    bestSeason: 'June-October',
    coverGradient: 'linear-gradient(135deg, #F5A020, #FF5533)',
    highlights: [
      'Great Migration crossings',
      'Big Five game drives',
      'Sunrise hot air balloon',
    ],
    hiddenGem: 'Book a walking safari in the Serengeti to track wildlife on foot for an intimate connection with nature.',
  },
  {
    id: 'kyoto',
    emoji: '🏯',
    name: 'Kyoto',
    country: 'Japan',
    countryCode: 'JP',
    tagline: 'Traditional temples and bamboo groves',
    description: 'Step back in time with ancient temples, serene gardens, geisha traditions, and exquisite Japanese culture.',
    days: 3,
    budgetUSD: 1200,
    ratingAverage: 4.8,
    cloneCount: 1876,
    tags: ['culture', 'history', 'nature'],
    personas: ['solo', 'couple', 'family'],
    bestSeason: 'March-May, November-December',
    coverGradient: 'linear-gradient(135deg, #7755F0, #F5A020)',
    highlights: [
      'Fushimi Inari thousands of gates',
      'Bamboo forest walks',
      'Traditional tea ceremonies',
    ],
    hiddenGem: 'Visit Philosopher\'s Path at dawn when cherry blossoms fall into the canal like pink snow.',
  },
  {
    id: 'amalficoast',
    emoji: '🌊',
    name: 'Amalfi Coast',
    country: 'Italy',
    countryCode: 'IT',
    tagline: 'Dramatic cliffs and Mediterranean romance',
    description: 'Drive along scenic coastal roads, explore pastel villages clinging to cliffs, and swim in turquoise waters.',
    days: 4,
    budgetUSD: 2000,
    ratingAverage: 4.8,
    cloneCount: 1432,
    tags: ['beach', 'romantic', 'food'],
    personas: ['couple', 'friends', 'family'],
    bestSeason: 'April-May, September-October',
    coverGradient: 'linear-gradient(135deg, #EF3F6A, #0BAADF)',
    highlights: [
      'Positano village',
      'Amalfi town exploring',
      'Coastal boat rides',
    ],
    hiddenGem: 'Hike to Praiano at night and dine at a waterfront restaurant with only candlelight and starlight above.',
  },
  {
    id: 'barcelona',
    emoji: '🎪',
    name: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    tagline: 'Gaudí architecture and Mediterranean vibes',
    description: 'Marvel at whimsical architecture, explore Gothic quarters, enjoy tapas culture, and relax on urban beaches.',
    days: 4,
    budgetUSD: 1600,
    ratingAverage: 4.6,
    cloneCount: 1765,
    tags: ['city', 'culture', 'food'],
    personas: ['friends', 'couple', 'solo'],
    bestSeason: 'April-May, September-October',
    coverGradient: 'linear-gradient(135deg, #FF5533, #F5A020)',
    highlights: [
      'Sagrada Familia basilica',
      'Park Güell mosaics',
      'Gothic Quarter wandering',
    ],
    hiddenGem: 'Climb to Bunkers del Carmel for sunset views over the city without the crowds of other viewpoints.',
  },
  {
    id: 'maui',
    emoji: '🌺',
    name: 'Maui',
    country: 'USA (Hawaii)',
    countryCode: 'US',
    tagline: 'Perfect beaches and volcanic landscapes',
    description: 'Relax on world-class beaches, hike volcanic peaks, snorkel coral reefs, and watch sunset from Haleakalā.',
    days: 5,
    budgetUSD: 2200,
    ratingAverage: 4.7,
    cloneCount: 987,
    tags: ['beach', 'nature', 'adventure'],
    personas: ['family', 'couple', 'friends'],
    bestSeason: 'April-May, September-November',
    coverGradient: 'linear-gradient(135deg, #0BBFA0, #0BAADF)',
    highlights: [
      'Haleakalā sunrise hike',
      'Snorkeling at Molokini Crater',
      'Road to Hana scenic drive',
    ],
    hiddenGem: 'Book a Maui Ocean Center aquarium visit at night for an eerie, intimate experience with nocturnal creatures.',
  },
  {
    id: 'swissalps',
    emoji: '🏔️',
    name: 'Swiss Alps',
    country: 'Switzerland',
    countryCode: 'CH',
    tagline: 'Chocolate, cheese, and mountain majesty',
    description: 'Hike through Alpine meadows, ride iconic mountain trains, explore charming villages, and savor Swiss delicacies.',
    days: 5,
    budgetUSD: 2500,
    ratingAverage: 4.8,
    cloneCount: 876,
    tags: ['mountains', 'adventure', 'nature'],
    personas: ['family', 'friends', 'adventure-seekers'],
    bestSeason: 'June-September',
    coverGradient: 'linear-gradient(135deg, #7755F0, #0BAADF)',
    highlights: [
      'Jungfrau region trekking',
      'Matterhorn views from Zermatt',
      'Interlaken adventure sports',
    ],
    hiddenGem: 'Take the cogwheel train to Rigi for clear morning light and views without crowds that Jungfrau gets.',
  },
  {
    id: 'marrakech',
    emoji: '🏜️',
    name: 'Marrakech',
    country: 'Morocco',
    countryCode: 'MA',
    tagline: 'Desert magic and medina mysteries',
    description: 'Wander souks, relax in riads, experience Berber culture, and venture into golden sand dunes.',
    days: 4,
    budgetUSD: 1100,
    ratingAverage: 4.6,
    cloneCount: 1234,
    tags: ['culture', 'budget', 'adventure'],
    personas: ['solo', 'friends', 'couple'],
    bestSeason: 'October-April',
    coverGradient: 'linear-gradient(135deg, #F5A020, #EF3F6A)',
    highlights: [
      'Jemaa el-Fnaa square',
      'Majorelle Garden',
      'Sahara dune camps',
    ],
    hiddenGem: 'Sleep under stars at a Sahara desert camp, wake before dawn, and ride camel to a secret rocky outcrop for sunrise.',
  },
  {
    id: 'costarica',
    emoji: '🌿',
    name: 'Costa Rica',
    country: 'Costa Rica',
    countryCode: 'CR',
    tagline: 'Rainforest adventures and pura vida',
    description: 'Zip-line through cloud forests, soak in hot springs, spot sloths and macaws, and embrace pura vida lifestyle.',
    days: 6,
    budgetUSD: 1800,
    ratingAverage: 4.7,
    cloneCount: 1432,
    tags: ['adventure', 'nature', 'wellness'],
    personas: ['family', 'friends', 'adventure-seekers'],
    bestSeason: 'December-April',
    coverGradient: 'linear-gradient(135deg, #0BBFA0, #FF5533)',
    highlights: [
      'Arenal volcano and hot springs',
      'Monteverde Cloud Forest',
      'Manuel Antonio beach and jungle',
    ],
    hiddenGem: 'Visit the hidden Nauyaca Waterfalls early morning when locals still fish—swim in pure solitude.',
  },
  {
    id: 'singapore',
    emoji: '🌏',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    tagline: 'Ultra-modern city-state with cosmopolitan charm',
    description: 'Experience futuristic architecture, incredible food diversity, lush Gardens by the Bay, and efficient urban exploration.',
    days: 3,
    budgetUSD: 1400,
    ratingAverage: 4.6,
    cloneCount: 876,
    tags: ['city', 'food', 'culture'],
    personas: ['solo', 'friends', 'business'],
    bestSeason: 'February-April, July-September',
    coverGradient: 'linear-gradient(135deg, #7755F0, #0BAADF)',
    highlights: [
      'Marina Bay Sands rooftop',
      'Gardens by the Bay at night',
      'Hawker food courts',
    ],
    hiddenGem: 'Take the train to Kranji Marshes Nature Reserve for wild mangrove hiking ten minutes from the urban jungle.',
  },
];

export const DestinationMap = Object.fromEntries(
  Destinations.map((d) => [d.id, d])
);
